# Generated by Django 3.0.4 on 2020-03-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cours', models.CharField(max_length=200, unique=True)),
                ('groupe', models.IntegerField(null=True)),
                ('quadrimestre', models.IntegerField()),
                ('nom_prof', models.CharField(max_length=200)),
                ('heure_debut', models.CharField(max_length=200)),
                ('heure_fin', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
