# Generated by Django 3.0.5 on 2020-05-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('cours', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('quadrimestre', models.IntegerField()),
                ('nombre_heure', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoursT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cours', models.CharField(max_length=200)),
                ('groupe', models.IntegerField(null=True)),
                ('quadrimestre', models.IntegerField()),
                ('nom_prof', models.CharField(max_length=200)),
                ('heure_debut', models.CharField(max_length=200)),
                ('heure_fin', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('jour', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ue',
            fields=[
                ('nom_ue', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('quadrimestre_ue', models.IntegerField()),
                ('nombre_credit_ue', models.IntegerField()),
                ('nombre_heure_ue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_user', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('Nombre_credit', models.IntegerField()),
                ('adresse', models.CharField(max_length=200)),
                ('annee', models.IntegerField()),
            ],
        ),
    ]
