# Generated by Django 3.0.5 on 2020-05-01 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelReading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='id_ue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExcelReading.Ue'),
        ),
        migrations.AddField(
            model_name='courst',
            name='id_cours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExcelReading.Cours'),
        ),
    ]
