# Generated by Django 3.0.4 on 2020-03-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelReading', '0002_remove_courst_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.CharField(max_length=200, unique=True)),
                ('quadrimestre', models.IntegerField()),
                ('nombre_credit', models.IntegerField()),
                ('nombre_heure', models.IntegerField()),
            ],
        ),
    ]
