# Generated by Django 3.0.5 on 2020-05-05 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelReading', '0003_remove_cours_id_ue'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='id_ue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExcelReading.Ue'),
        ),
    ]
