# Generated by Django 3.0.5 on 2020-05-13 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelReading', '0004_cours_id_ue'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExcelReading.Cours')),
                ('nom_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExcelReading.User')),
            ],
        ),
    ]
