# Generated by Django 3.0.5 on 2020-05-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelReading', '0005_usercourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='nom_etudiant',
        ),
    ]
