# Generated by Django 3.0.5 on 2020-04-03 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelReading', '0005_courst_jour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ue', models.CharField(max_length=200, unique=True)),
                ('quadrimestre_ue', models.IntegerField()),
                ('nombre_credit_ue', models.IntegerField()),
                ('nombre_heure_ue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_user', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('Nombre_credit', models.IntegerField()),
                ('adresse', models.CharField(max_length=200)),
                ('annee', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='nombre_credit',
        ),
        migrations.AddField(
            model_name='courst',
            name='id_cours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExcelReading.Cours'),
        ),
        migrations.AddField(
            model_name='ue',
            name='id_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='User', to='ExcelReading.User'),
        ),
        migrations.AddField(
            model_name='cours',
            name='id_ue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExcelReading.Ue'),
        ),
    ]
